name: flutter_tsc_utils_example
publish_to: none
description: Example app for flutter_tsc_utils.

environment:
  sdk: ^3.11.1

dependencies:
  flutter:
    sdk: flutter
  flutter_tsc_utils:
    path: ../

flutter:
  uses-material-design: true
